version: '3'

services:
    db:
        image: postgres
        ports:
            - "5432:5432"
        env_file:
            - ./.env
    api:
        build: .
        command: ./start-server.sh
        volumes:
            - .:/code/
        ports:
            - "8080:8080"
        env_file:
            - ./.env
        depends_on:
            - db
