# Generated by Django 4.1.4 on 2022-12-10 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_weekend_open', models.BooleanField()),
                ('is_sunday_open', models.BooleanField()),
                ('has_break', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.IntegerField()),
                ('start_minute', models.IntegerField()),
                ('end_hour', models.IntegerField()),
                ('end_minute', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='break_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_schedule', to='branches.schedule'),
        ),
        migrations.AddField(
            model_name='branch',
            name='mf_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mf_schedule', to='branches.schedule'),
        ),
        migrations.AddField(
            model_name='branch',
            name='operations',
            field=models.ManyToManyField(to='branches.operation'),
        ),
        migrations.AddField(
            model_name='branch',
            name='satsun_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satsun_schedule', to='branches.schedule'),
        ),
    ]
