# Generated by Django 4.1.4 on 2022-12-10 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_operation_appointment_duration_operation_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branch_id',
        ),
    ]
