# Generated by Django 4.1.4 on 2022-12-10 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_operation_appointment_duration_operation_description_and_more'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='branches.branch'),
        ),
    ]
