# Generated by Django 4.1.4 on 2022-12-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rename_date_appointment_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='uuid',
            field=models.UUIDField(default='62e0cade-cfde-4384-acb8-3bca0449dceb'),
            preserve_default=False,
        ),
    ]
